app_name = "go-crawler"
app_port = "8080"
db_host = "0.0.0.0"
db_password = "postgres"
db_username = "postgres"


[debug]
db_name = "go_crawler_development"
db_port = "5432"

[test]
db_name = "go_crawler_test"
db_port = "5433"
